# Generated by Django 4.2.7 on 2025-12-26 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('will_use_app', models.BooleanField(default=False)),
                ('okay_with_emails', models.BooleanField(default=False)),
                ('would_pay', models.BooleanField(default=False)),
                ('use_case', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
